### ISSUE TITLE
Add reference for the dayTemp formula

### ISSUE THREAD

**Issue by GeraldCNelson** [cropmodels/meteor#4]
Please add the reference to this function
Reference: Bouman, B. A. M., Kropff, M. J., Tuong, T. P., Wopereis M.C.S., ten Berge, H. F. M., & van Laar, H. H. (2001).  ORYZA2000: modeling lowland rice. http://books.irri.org/9712201716_content.pdf in the help file.

**Comment by rhijmans** [comment]
Not the best reference
